extraSources implementation without extraSourcesDir
mlabs-haskell/proto.nix pull request #17
Opened 2024-06-14 11:26 UTC by chfanghr

2024-06-14 12:39 UTC, bladyjoker requested changes
I propose a different I'd argue less involved approach.

Make a protoc.nix instead of this shenanigans in protobuf-with-extra-sources.nix

With protoc.nix you can just use it and yuo'd end up with

```
protocCall {
  inherit src
  inherit protos;
  imports = extraSources;
  plugin = pkgs.protoc-gen-doc;
  pluginOpts = {
    doc_out = "$out";
    doc_opt = "${docType},api.md"
  };
}
```

You reuse protocCall everywhere.

2024-06-14 12:39 UTC, bladyjoker commented on src/protobuf-with-extra-sources.nix
I find that this is complicating matters.

Why not make a protoc.nix instead much like https://github.com/mlabs-haskell/lambda-buffers/blob/main/extras/lbf-nix/lbf-build.nix

This is a library that gives you a way to just construct the shell invocation of protoc and then you use this instead in all protoc invocations

2024-06-14 12:39 UTC, bladyjoker commented on src/combined.nix
> +      ourProtobuf
This is very round about and would rather you revert back to the obvious solution.

2024-06-14 12:39 UTC, bladyjoker commented on src/doc-proto.nix
> +      ${builtins.concatStringsSep " " protos};
With protoc.nix you can just use it and yuo'd end up with

```
protocCall {
  inherit src
  inherit protos;
  imports = extraSources;
  plugin = pkgs.protoc-gen-doc;
  pluginOpts = {
    doc_out = "$out";
    doc_opt = "${docType},api.md"
  };
}
```

2024-06-14 12:42 UTC, chfanghr commented on src/combined.nix
> +      ourProtobuf
The whole point is to make protobuf recognize extra sources in the devshell, how do you do it otherwise? We may as well remove the devshell at this point.

2024-06-14 13:00 UTC, bladyjoker commented on src/combined.nix
> +      ourProtobuf
Ok I see, let me think

2024-06-14 13:14 UTC, bladyjoker commented on src/protobuf-with-extra-sources.nix
Ok this is a wrong name first and foremost. This is `protoc-with-extra-sources.nix`

2024-06-14 13:14 UTC, bladyjoker commented on src/protobuf-with-extra-sources.nix
> +})
I don't know what this does tbh

2024-06-14 13:14 UTC, bladyjoker commented on src/protobuf-with-extra-sources.nix
> +  '';
Don't call this `our` it;s completely off, call this `protocWithExtraSources`, as that's what it is. Also apply this naming throughout.

2024-06-14 13:28 UTC, chfanghr commented on src/protobuf-with-extra-sources.nix
> +})
Change some properties in the derivation produced by `linkFarm` and produce a new one.

2024-06-14 13:30 UTC, chfanghr commented on src/protobuf-with-extra-sources.nix
The derivation it produce does have everthing from the original protobuf package except the main program, hence the name

2024-06-17 12:08 UTC, bladyjoker approved these changes
Ship it! Thanks mate!

2024-06-17 12:15 UTC, merged